### ISSUE TITLE
Plans to add to PyPI?

### ISSUE THREAD

**Issue by ubalklen** [kdschlosser/python_msvc#11]
Any chance this package gets upload to PyPI, so users can install it using `pip install pyton-msvc`?

**Comment by kdschlosser** [comment]
it is on pypi.

pip install pyMSVC

**Comment by ubalklen** [comment]
My bad. Maybe this info should be added to readme?

**Comment by kdschlosser** [comment]
it is in the readme. At the bottom it tells you how to add it to your build system.

**Comment by ubalklen** [comment]
In my case, I didn't want to jump straight to setting up the building process and intended to import the package myself to see how it works. I skimmed over the readme and couldn't find instructions to install from PyPI, and that's why I've opened this issue.

But now I understand that this package is really meant to be used along with the building process and maybe it doesn't make much sense to install it in an standalone way. Thank you very much.

**Comment by kdschlosser** [comment]
It does make sense for testing purposes. If you want to update the readme and add that information you are more than welcome to do that. I would rather have you do it so this way there is a record of who came up with the idea and implemented the change.  

Did this library solve the problem you were having??... 

I am thinking about expanding it to fix the multiprocess build system that doesn't work for MSVC when using setuptools/distutils. That has always been a kind of annoyance especially when compiling a larger project. setuptools also doesn't have the easiest handling of compiling dynamic libraries using an export file. 

I already have a rough draft for the multiprocess system and handling of a manifest. I have even gone as far as generating an export file using C header files. it only works for C headers. I have also written aa script that will take those same C header files and create a python binding to aa dynamic library using ctypes.

unfortunately there are no build systems that I would put into the category of working fantastic with MSVC. and I have been toying with the idea of making one.
